Repository ManageIQ/manageiq-decorators, pull requests merged in 2020-10, with the labels that each got.

#33 Added StorageResourceDecorator
  app/decorators/storage_resource_decorator.rb
Labels: enhancement

#34 Plugin Generator Updates
  .codeclimate.yml
  .gitignore
  .rspec
  .rspec_ci
  .rubocop.yml
  .rubocop_cc.yml
  .rubocop_local.yml
  .travis.yml
  .yamllint
  Gemfile
  LICENSE.txt
  README.md
  Rakefile
  bin/ci/after_script
  bin/update
  bundler.d/.keep
  config/settings.yml
  lib/manageiq-decorators.rb
  lib/manageiq/decorators/engine.rb
  lib/manageiq/decorators/version.rb
  lib/tasks/README.md
  lib/tasks_private/spec.rake
  locale/.keep
  manageiq-decorators.gemspec
  spec/lib/miq_decorator_spec.rb
  spec/spec_helper.rb
Labels: developer

#35 Test with ruby 2.5.8 and 2.6.6
  .travis.yml
Labels: dependencies

#36 Use manageiq-style
  .codeclimate.yml
  .rubocop.yml
  .rubocop_cc.yml
  manageiq-decorators.gemspec
Labels: developer, enhancement
