Repository ManageIQ/manageiq-decorators, pull requests merged in 2022-02, with the labels that each got.

#63 Remove Hakiri
  README.md
Labels: cleanup, developer

#64 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-decorators.gemspec
Labels: test, developer

#66 fix vendor IBM Z icon
  app/assets/images/svg/vendor-ibm_z_vm.svg
Labels: bug, najdorf/yes?

#67 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: test, developer
