Repository ManageIQ/manageiq-decorators, pull requests merged in 2022-05, with the labels that each got.

#72 Update apt-cache before running apt-get install
  bin/before_install
Labels: bug, test

#71 Add manual option for CI github workflow
  .github/workflows/ci.yaml
Labels: test

#73 Fix for error when opening C&U Collection
  app/decorators/host_decorator.rb
Labels: bug, najdorf/yes?
