Repository ManageIQ/manageiq-decorators, pull requests merged in 2024-02, with the labels that each got.

#98 Test with ruby 3.1 and 3.0
  .github/workflows/ci.yaml
Labels: test

#99 Remove usage of eval functions in ui-classic
  app/decorators/service_template_decorator.rb
Labels: bug

#100 [RADJABOV] Test radjabov with ruby 3.1
  .github/workflows/ci.yaml
Labels: test, ruby3.1
